C#And.Net Workspace/ASP.Net/Day11/ContosoUniversityDemo/Models/Instructor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ContosoUniversityDemo.Models
{
    public class Instructor
    {
        [Key]
        public int InstructorID { get; set; }

        [DisplayName("LastName")]
        [Required(ErrorMessage="LastName是必填选项!")]
        [StringLength(30, ErrorMessage="最大长度不能超过30")]
        public string LastName { get; set; }

        [DisplayName("FirstName")]
        [Required(ErrorMessage="FirstName是必填项")]
        [StringLength(30, ErrorMessage="最大长度不能超过30")]
        public string FirstMidName { get; set; }

        [DisplayName("HireDate")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode=true, DataFormatString="{0:yyyy-MM-dd}")]        
        public DateTime HireDate { get; set; }

        [DisplayName("FullName")]
        public string FullName 
        {
            get { return LastName + ", " + FirstMidName; }
        }

        //  如果一个导航属性可以容纳多个实体，则它的类型必须实现ICollection<T>接口，例如List<T>，但不能是IEnumerable<T>，因为它不实现Add
        public virtual ICollection<Course> Courses { get; set; }        
        public virtual OfficeAssignment OfficeAssignment { get; set; }
    }
}

C#And.Net Workspace/ASP.Net/Day11/ContosoUniversityDemo/Controllers/InstructorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Net;
using ContosoUniversityDemo.Models;
using ContosoUniversityDemo.DAL;
using ContosoUniversityDemo.ViewModels;

namespace ContosoUniversityDemo.Controllers
{
    //  1、延迟加载(Lazy Loading)。当实体第一次被读取时，相关数据不会被获取。但是，当第一次尝试存取导航属性时，该导航属性所需的数据会自动加载。
    //  结果会使用多个查询发送到数据库——一次是读取实体本身，然后是每个相关的实体。DbContext类默认是使用延迟加载的。

    //  2、预先加载(Eager Loading)。当实体读取时立即获取与该实体相关的数据。
    //  这通常会导致在单个连接查询中检索出所有所需要的数据。可以通过使用Include方法来指定预先加载。

    //  3、显式加载(Explicit Loading)。有点类似于延迟加载，只是你在代码中显式地获取相关数据。您访问一个导航属性时，它不会自动加载。
    //  需要通过使用实体的对象状态管理器并调用集合上的Collection.Load方法或通过持有单个实体的属性的Reference.Load方法来手动加载相关数据。

    public class InstructorController : Controller
    {
        private SchoolContext dbContext = new SchoolContext();

        //  代码首先创建视图模型的实例并将讲师列表放进模型中，该代码指定在OfficeAssignment和Courses导航属性上使用预先加载。
        //  第二个Include方法加载课程，并且为每个课程预先加载Department导航属性。
        public ActionResult Index(int? id, int? courseID)
        {
            var viewmodel = new InstructorIndexData();
            viewmodel.Instructors = dbContext.Instructors
                .Include(i => i.OfficeAssignment)
                .Include(i => i.Courses.Select(c => c.Department))
                .OrderBy(i => i.LastName);
            if (id != null)
            {
                ViewBag.InstructorID = id.Value;
                viewmodel.Courses = viewmodel.Instructors.Where(i => i.InstructorID == id.Value).Single().Courses;
            }
            if (courseID != null)
            {
                ViewBag.CourseID = courseID.Value;
                //  延迟加载
                //  viewmodel.Enrollments = viewmodel.Courses.Where(c => c.CourseID == courseID.Value).Single().Enrollments;
              
                //  显式加载
                var selectedCourse = viewmodel.Courses.Where(c => c.CourseID == courseID.Value).Single();
                dbContext.Entry(selectedCourse).Collection(x => x.Enrollments).Load();
                foreach (Enrollment enrollmentItem in selectedCourse.Enrollments)
                {
                    dbContext.Entry(enrollmentItem).Reference(x => x.Student).Load();
                }
                viewmodel.Enrollments = selectedCourse.Enrollments;
            }
            return View(viewmodel);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int InstructorID = (int)id;
            var instructor = dbContext.Instructors.Include(i => i.OfficeAssignment).Where(i => i.InstructorID == InstructorID).Single();
            if (instructor == null)
            {
                return HttpNotFound();
            }
            return View(instructor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind]Instructor instructor)
        {
            return RedirectToAction("Index");
        }

        public ActionResult Detail(int? id)
        {
            return View();
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int InstructorID = (int)id;
            var instructor = dbContext.Instructors.Find(InstructorID);
            if (instructor == null)
            {
                return HttpNotFound();
            }
            dbContext.Instructors.Remove(instructor);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        //  释放数据库上下文
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                dbContext.Dispose();
            }
            base.Dispose(disposing);
        }
	}
}

C#And.Net Workspace/ASP.Net/Day11/ContosoUniversityDemo/Views/Instructor/Create.cshtml
@model ContosoUniversityDemo.Models.Instructor
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
<h3>Create A New Instructor</h3>

@using (Html.BeginForm("Create", "Instructor", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.LastName)
        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.FirstMidName)
        @Html.TextBoxFor(m => m.FirstMidName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.HireDate)
        @Html.TextBoxFor(m => m.HireDate, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.OfficeAssignment.Location)
        @Html.TextBoxFor(m => m.OfficeAssignment.Location, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label class="checkbox-inline">
            
        </label>
    </div>
}

C#And.Net Workspace/ASP.Net/Day11/ContosoUniversityDemo/Views/Instructor/Edit.cshtml
@model ContosoUniversityDemo.Models.Instructor
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
<h3>Instructor Edit</h3>

@using (Html.BeginForm("Edit", "Instructor", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()
    
    <div class="form-group">
        <label>@Html.DisplayNameFor(m => m.LastName)</label>
        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.LastName, null, new { style = "color:red;font-weight:bold;" })
    </div>
    <div class="form-group">
        <label>@Html.DisplayNameFor(m => m.FirstMidName)</label>
        @Html.TextBoxFor(m => m.FirstMidName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.FirstMidName, null, new { style = "color:red;font-weight:bold;" })
    </div>
    <div class="form-group">
        <label>@Html.DisplayNameFor(m => m.HireDate)</label>
        @Html.TextBoxFor(m => m.HireDate, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.HireDate, null, new { style = "color:red;font-weight:bold;" })
    </div>
    <div class="form-group">
        <label>@Html.DisplayNameFor(m => m.OfficeAssignment.Location)</label>
        @Html.TextBoxFor(m => m.OfficeAssignment.Location, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.OfficeAssignment.Location, null, new { style = "color:red;font-weight:bold;" })
    </div>
    
    <input type="submit" value="Save" class="btn btn-success">
}
<br />
<p>@Html.ActionLink("Back To InstructorIndex", "Index", null, new { style = "text-decoration:none;" })</p>

C#And.Net Workspace/ASP.Net/Day11/ContosoUniversityDemo/Views/Instructor/Index.cshtml
@model ContosoUniversityDemo.ViewModels.InstructorIndexData
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Instructor</h2>
<p>
    @Html.ActionLink("Create A New Instructor", "Create", null, new { @class = "btn btn-success" })
</p>
<table class="table table-hover">
    <tr>
        <th>LastName</th>
        <th>FirstName</th>
        <th>HireDate</th>
        <th>Office</th>
        <th></th>
    </tr>
    @foreach (var item in Model.Instructors)
    {
        string selectedRow = "";
        if (item.InstructorID == ViewBag.InstructorID)
        {
            selectedRow = "success";
        }
        <tr class="@selectedRow">
            <td>@Html.DisplayFor(m => item.LastName)</td>
            <td>@Html.DisplayFor(m => item.FirstMidName)</td>
            <td>@Html.DisplayFor(m => item.HireDate)</td>
            <td>
                @if(item.OfficeAssignment != null)
                {
                    @Html.DisplayFor(m => item.OfficeAssignment.Location)
                }
            </td>
            <td>@Html.ActionLink("Select", "Index", null, new { id = item.InstructorID }, new { style = "text-decoration:none;" }) | 
                @Html.ActionLink("Edit", "Edit", null, new { id = item.InstructorID }, new { style = "text-decoration:none;" }) |
                @Html.ActionLink("Detail", "Detail", null, new { id = item.InstructorID }, new { style = "text-decoration:none;" }) |
                @Html.ActionLink("Delete", "Delete", null, new { id = item.InstructorID }, new { style = "text-decoration:none;" })
            </td>
        </tr>
    }
</table>

@if (Model.Courses != null)
{
    <br />
    <h3>Courses Taught By Selected Instructor</h3>
    <table class="table table-hover">
        <tr>
            <th></th>
            <th>Number</th>
            <th>Title</th>
            <th>Department</th>
        </tr>
        @foreach (var item in Model.Courses)
        {
            string selectedRow = "";
            if (item.CourseID == ViewBag.CourseID)
            {
                selectedRow = "success";
            }
            <tr class="@selectedRow">
                <td>@Html.ActionLink("Select", "Index", null, new { id = ViewBag.InstructorID, courseID = item.CourseID }, new { style = "text-decoration:none;" })</td>
                <td>@Html.DisplayFor(m => item.CourseID)</td>
                <td>@Html.DisplayFor(m => item.Title)</td>
                <td>@Html.DisplayFor(m => item.Department.Name)</td>
            </tr>
        }
    </table>
}

@if (Model.Enrollments != null)
{
    <br />
    <h3>Students Enrolled In Select Course</h3>
    <table class="table table-hover">
        <tr>
            <th>Name</th>
            <th>Grade</th>
        </tr>
        @foreach(var item in Model.Enrollments)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Student.FullName)</td>
                <td>@Html.DisplayFor(m => item.Grade)</td>
            </tr>
        }
    </table>
}

<!--
@*
<h3>Courses Taught By Selected Instructor</h3>
<table class="table table-hover">
    <tr>
        <th></th>
        <th>Number</th>
        <th>Title</th>
        <th>Department</th>
    </tr>
    @foreach (var item in Model.Courses)
    {
        <tr>
            <td>@Html.ActionLink("Select", "Index", null, new { id = ViewBag.InstructorID, courseID = item.CourseID }, new { style = "text-decoration:none;" })</td>
            <td>@Html.DisplayFor(m => item.CourseID)</td>
            <td>@Html.DisplayFor(m => item.Title)</td>
            <td>@Html.DisplayFor(m => item.Department.Name)</td>
        </tr>
    }
</table>
*@
-->